<?php

use Illuminate\Database\Seeder;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('employees')->insert([
            [
                'photo' => '',
                'code' => 'HR0001',
                'status' => '1',
                'name' => 'HR Manager',
                'gender' => '1',
                'date_of_birth' => '',
                'date_of_joining' => '',
                'number' => '9999999999',
                'qualification' => '',
                'emergency_number' => '',
                'father_name' => '',
                'current_address' => '',
                'permanent_address' => '',
                'formalities' => '',
                'offer_acceptance' => '',
                'probation_period' => '',
                'date_of_confirmation' => '',
                'department' => '',
                'salary' => '',
                'account_number' => '',
                'bank_name' => '',
                'date_of_resignation' => '',
                'notice_period' => '',
                'last_working_day' => '',
                'full_final' => '',
                'user_id' => '1'
            ],
            [
                'photo' => '',
                'code' => 'FE001',
                'status' => '1',
                'name' => 'Bachtiar Fatur Rohim',
                'gender' => '1',
                'date_of_birth' => '',
                'date_of_joining' => '',
                'number' => '9999999999',
                'qualification' => '',
                'emergency_number' => '',
                'father_name' => '',
                'current_address' => '',
                'permanent_address' => '',
                'formalities' => '',
                'offer_acceptance' => '',
                'probation_period' => '',
                'date_of_confirmation' => '',
                'department' => '',
                'salary' => '',
                'account_number' => '',
                'bank_name' => '',
                'date_of_resignation' => '',
                'notice_period' => '',
                'last_working_day' => '',
                'full_final' => '',
                'user_id' => '2'
            ],
            [
                'photo' => '',
                'code' => 'DCK001',
                'status' => '1',
                'name' => 'Dikcy Saputra',
                'gender' => '1',
                'date_of_birth' => '',
                'date_of_joining' => '',
                'number' => '9999999999',
                'qualification' => '',
                'emergency_number' => '',
                'father_name' => '',
                'current_address' => '',
                'permanent_address' => '',
                'formalities' => '',
                'offer_acceptance' => '',
                'probation_period' => '',
                'date_of_confirmation' => '',
                'department' => '',
                'salary' => '',
                'account_number' => '',
                'bank_name' => '',
                'date_of_resignation' => '',
                'notice_period' => '',
                'last_working_day' => '',
                'full_final' => '',
                'user_id' => '3'
            ],
            [
                'photo' => '',
                'code' => 'AND001',
                'status' => '1',
                'name' => 'Andi Gusta',
                'gender' => '1',
                'date_of_birth' => '',
                'date_of_joining' => '',
                'number' => '9999999999',
                'qualification' => '',
                'emergency_number' => '',
                'father_name' => '',
                'current_address' => '',
                'permanent_address' => '',
                'formalities' => '',
                'offer_acceptance' => '',
                'probation_period' => '',
                'date_of_confirmation' => '',
                'department' => '',
                'salary' => '',
                'account_number' => '',
                'bank_name' => '',
                'date_of_resignation' => '',
                'notice_period' => '',
                'last_working_day' => '',
                'full_final' => '',
                'user_id' => '4'
            ],
            [
                'photo' => '',
                'code' => 'TM001',
                'status' => '1',
                'name' => 'Tama',
                'gender' => '1',
                'date_of_birth' => '',
                'date_of_joining' => '',
                'number' => '9999999999',
                'qualification' => '',
                'emergency_number' => '',
                'father_name' => '',
                'current_address' => '',
                'permanent_address' => '',
                'formalities' => '',
                'offer_acceptance' => '',
                'probation_period' => '',
                'date_of_confirmation' => '',
                'department' => '',
                'salary' => '',
                'account_number' => '',
                'bank_name' => '',
                'date_of_resignation' => '',
                'notice_period' => '',
                'last_working_day' => '',
                'full_final' => '',
                'user_id' => '5'
            ],
            [
                'photo' => '',
                'code' => 'OWN001',
                'status' => '1',
                'name' => 'Owen',
                'gender' => '1',
                'date_of_birth' => '',
                'date_of_joining' => '',
                'number' => '9999999999',
                'qualification' => '',
                'emergency_number' => '',
                'father_name' => '',
                'current_address' => '',
                'permanent_address' => '',
                'formalities' => '',
                'offer_acceptance' => '',
                'probation_period' => '',
                'date_of_confirmation' => '',
                'department' => '',
                'salary' => '',
                'account_number' => '',
                'bank_name' => '',
                'date_of_resignation' => '',
                'notice_period' => '',
                'last_working_day' => '',
                'full_final' => '',
                'user_id' => '6'
            ],
            [
                'photo' => '',
                'code' => 'BKO001',
                'status' => '1',
                'name' => 'Biko',
                'gender' => '1',
                'date_of_birth' => '',
                'date_of_joining' => '',
                'number' => '9999999999',
                'qualification' => '',
                'emergency_number' => '',
                'father_name' => '',
                'current_address' => '',
                'permanent_address' => '',
                'formalities' => '',
                'offer_acceptance' => '',
                'probation_period' => '',
                'date_of_confirmation' => '',
                'department' => '',
                'salary' => '',
                'account_number' => '',
                'bank_name' => '',
                'date_of_resignation' => '',
                'notice_period' => '',
                'last_working_day' => '',
                'full_final' => '',
                'user_id' => '7'
            ],
            [
                'photo' => '',
                'code' => 'LEO001',
                'status' => '1',
                'name' => 'Leo Dandy',
                'gender' => '1',
                'date_of_birth' => '',
                'date_of_joining' => '',
                'number' => '9999999999',
                'qualification' => '',
                'emergency_number' => '',
                'father_name' => '',
                'current_address' => '',
                'permanent_address' => '',
                'formalities' => '',
                'offer_acceptance' => '',
                'probation_period' => '',
                'date_of_confirmation' => '',
                'department' => '',
                'salary' => '',
                'account_number' => '',
                'bank_name' => '',
                'date_of_resignation' => '',
                'notice_period' => '',
                'last_working_day' => '',
                'full_final' => '',
                'user_id' => '8'
            ],
            [
                'photo' => '',
                'code' => 'RZK001',
                'status' => '1',
                'name' => 'Muhammad Rizky',
                'gender' => '1',
                'date_of_birth' => '',
                'date_of_joining' => '',
                'number' => '9999999999',
                'qualification' => '',
                'emergency_number' => '',
                'father_name' => '',
                'current_address' => '',
                'permanent_address' => '',
                'formalities' => '',
                'offer_acceptance' => '',
                'probation_period' => '',
                'date_of_confirmation' => '',
                'department' => '',
                'salary' => '',
                'account_number' => '',
                'bank_name' => '',
                'date_of_resignation' => '',
                'notice_period' => '',
                'last_working_day' => '',
                'full_final' => '',
                'user_id' => '9'
            ]
        ]);
    }
}
